[Desktop Entry]
Type=Service
Exec=blubb
Comment=Finds and runs PHPUnit tests.
Comment[nl]=Testen van PHPUnit vinden en uitvoeren.
Comment[sv]=Söker efter och kör PHPUnit-tester.
Comment[uk]=Знаходить і запускає тести PHPUnit.
Comment[x-test]=xxFinds and runs PHPUnit tests.xx
Name=PHPUnit Integration
Name[nl]=Integratie van PHPUnit
Name[sv]=Integrering av PHPUnit
Name[uk]=Інтеграція з PHPUnit
Name[x-test]=xxPHPUnit Integrationxx
GenericName=PHPUnit Integration
GenericName[nl]=Integratie van PHPUnit
GenericName[sv]=Integrering av PHPUnit
GenericName[uk]=Інтеграція з PHPUnit
GenericName[x-test]=xxPHPUnit Integrationxx
Icon=php
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevphpunitprovider
X-KDE-PluginInfo-Name=kdevphpunitprovider
X-KDE-PluginInfo-Author=Miha Čančula
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-Category=Testing
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Category=Global
X-KDevelop-Interfaces=org.kdevelop.ITestProvider
X-KDevelop-Mode=NoGUI
