[Desktop Entry]
Type=Service
Exec=blubb
Comment=Finds and runs PHPUnit tests.
Comment[ca]=Cerca i executa proves del PHPUnit.
Comment[ca@valencia]=Busca i executa proves del PHPUnit.
Comment[es]=Encuentra y ejecuta pruebas PHPUnit.
Comment[nl]=Testen van PHPUnit vinden en uitvoeren.
Comment[pt]=Procura e executa os testes do PHPUnit.
Comment[sk]=Nájde a spustí PHPUnit testy.
Comment[sv]=Söker efter och kör PHPUnit-tester.
Comment[uk]=Пошук і запуск перевірок PHPUnit.
Comment[x-test]=xxFinds and runs PHPUnit tests.xx
Name=PHPUnit Integration
Name[ca]=Integració del PHPUnit
Name[ca@valencia]=Integració del PHPUnit
Name[es]=Integración de PHPUnit
Name[nl]=Integratie van PHPUnit
Name[pt]=Integração com o PHPUnit
Name[sk]=Integrácia PHPUnit
Name[sv]=Integrering av PHPUnit
Name[uk]=Інтеграція PHPUnit
Name[x-test]=xxPHPUnit Integrationxx
GenericName=PHPUnit Integration
GenericName[ca]=Integració del PHPUnit
GenericName[ca@valencia]=Integració del PHPUnit
GenericName[es]=Integración de PHPUnit
GenericName[nl]=Integratie van PHPUnit
GenericName[pt]=Integração com o PHPUnit
GenericName[sk]=Integrácia PHPUnit
GenericName[sv]=Integrering av PHPUnit
GenericName[uk]=Інтеграція PHPUnit
GenericName[x-test]=xxPHPUnit Integrationxx
Icon=php
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevphpunitprovider
X-KDE-PluginInfo-Name=kdevphpunitprovider
X-KDE-PluginInfo-Author=Miha Čančula
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-Category=Testing
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Category=Global
X-KDevelop-Interfaces=org.kdevelop.ITestProvider
X-KDevelop-Mode=NoGUI
