[Desktop Entry]
Icon=application-x-php
Type=Service
ServiceTypes=KCModule

X-KDE-Library=kdevplatform/@KDEV_PLUGIN_VERSION@/kcm/kcm_kdevphpdocs
X-KDE-FactoryName=kdevphpdocs_config
X-KDE-ParentApp=kdevplatform
X-KDE-ParentComponents=kdevplatform,kdevphpdocs
X-KDE-CfgDlgHierarchy=DOCUMENTATION
X-KDE-Weight=150

Name=PHP Documentation
Name[ca]=Documentació de PHP
Name[ca@valencia]=Documentació de PHP
Name[cs]=Dokumentace PHP
Name[de]=PHP-Dokumentation
Name[el]=PHP τεκμηρίωση
Name[en_GB]=PHP Documentation
Name[es]=Documentación de PHP
Name[et]=PHP dokumentatsioon
Name[eu]=PHP dokumentazioa
Name[fi]=PHP:n dokumentaatio
Name[fr]=Documentation PHP
Name[gl]=Documentación de PHP
Name[hu]=PHP dokumentáció
Name[it]=Documentazione PHP
Name[ka]=PHP-ის დოკუმენტაცია
Name[ko]=PHP 문서
Name[nb]=PHP-dokumentasjon
Name[nl]=PHP-documentatie
Name[nn]=PHP-dokumentasjon
Name[pl]=Dokumentacja PHP
Name[pt]=Documentação de PHP
Name[pt_BR]=Documentação de PHP
Name[ru]=Документация по PHP
Name[sk]=Dokumentácia PHP
Name[sl]=Dokumentacija za PHP
Name[sv]=PHP-dokumentation
Name[tr]=PHPUnit Belgelendirmesi
Name[uk]=Документація з PHP
Name[x-test]=xxPHP Documentationxx
Name[zh_CN]=PHP 文档
Name[zh_TW]=PHP 說明文件
