/*
    This file is part of the KDE project
    SPDX-FileCopyrightText: 2012 Milian Wolff <mail@milianw.de>

    SPDX-License-Identifier: LGPL-2.0-or-later
*/
#ifndef KDEVPHPDOCS_VERSION_H
#define KDEVPHPDOCS_VERSION_H

#include <kdeversion.h>

#define KDEVPHPDOCS_MAJOR_VERSION @KDEVPHPDOCS_VERSION_MAJOR@
#define KDEVPHPDOCS_MINOR_VERSION @KDEVPHPDOCS_VERSION_MINOR@
#define KDEVPHPDOCS_PATCH_VERSION @KDEVPHPDOCS_VERSION_PATCH@

#define KDEVPHPDOCS_VERSION_STR "@KDEVPHPDOCS_VERSION_MAJOR@.@KDEVPHPDOCS_VERSION_MINOR@.@KDEVPHPDOCS_VERSION_PATCH@"

#define KDEVPHPDOCS_VERSION KDE_MAKE_VERSION(@KDEVPHPDOCS_VERSION_MAJOR@, @KDEVPHPDOCS_VERSION_MINOR@, @KDEVPHPDOCS_VERSION_PATCH@)

#endif
