
/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

/*  This code generated by: 
 *      Author : thomas
 *      Date   : Mon Sep 1 2003
 */



#ifndef CPPCODEDOCUMENTATION_H
#define CPPCODEDOCUMENTATION_H

#include <qstring.h>
#include "../codecomment.h"

class ClassifierCodeDocument; 

/**
  * class CPPCodeDocumentation
  * A CPP code comment. There is only a single styles of comments: 
  * these are simply started with double slash sequence and no terminating
  * characters
  */

class CPPCodeDocumentation : virtual public CodeComment
{
	Q_OBJECT
public:

	// Constructors/Destructors
	//  


	/**
	 * Constructors
	 */
	CPPCodeDocumentation ( ClassifierCodeDocument * doc, const QString & text = "");

	/**
	 * Empty Destructor
	 */
	virtual ~CPPCodeDocumentation ( );

	// Public attributes
	//  

	// Other
	//  

        /**
         * Save the XMI representation of this object
         * @return      bool    status of save
         */
        virtual bool saveToXMI ( QDomDocument & doc, QDomElement & root );

        /**
         * load params from the appropriate XMI element node.
         */
        virtual void loadFromXMI ( QDomElement & root );

	/**
	 * @return	QString
	 */
	QString toString ( );


protected:

private:

};

#endif // CPPCODEDOCUMENTATION_H
