
/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

/*  This code generated by: 
 *      Author : thomas
 *      Date   : Thu Aug 28 2003
 */

#ifndef CPPCLASSIFIERCODEDOCUMENT_H
#define CPPCLASSIFIERCODEDOCUMENT_H

#include <qstring.h>
#include "../classifiercodedocument.h"
#include "../classifier.h"
#include "../hierarchicalcodeblock.h"
#include "classifierinfo.h"
//#include "cppcodeclassfield.h"
//#include "cppcodeoperation.h"

class CPPCodeGenerator;
class CPPClassDeclarationBlock;
class CPPCodeGenerationPolicy;

/**
  * class CPPClassifierCodeDocument
  * A CPP UMLClassifier Code Document.
  */

class CPPClassifierCodeDocument : public ClassifierCodeDocument
{
	Q_OBJECT
public:

	// Constructors/Destructors
	//  

	/**
	 * Constructor
	 */
	CPPClassifierCodeDocument (UMLClassifier * classifier , CPPCodeGenerator * parent);

	/**
	 * Empty Destructor
	 */
	virtual ~CPPClassifierCodeDocument ( );

	/**
	 * Get the dialog widget which allows user interaction with the object parameters.
	 * @return	CodeDocumentDialog
	 */
	//CodeDocumentDialog getDialog ( );

	QString scopeToCPPDecl(Uml::Scope scope); 

	QString getCPPClassName (QString name);

	// QString getPath();

	/** add a code operation to this cpp classifier code document.
	 *  @return bool which is true IF the code operation was added successfully
	 */
	bool addCodeOperation (CodeOperation * op );

      /**
         * create a new CodeAccesorMethod object belonging to this CodeDocument.
         * @return      CodeAccessorMethod
         */
        virtual CodeAccessorMethod * newCodeAccessorMethod( CodeClassField *cf, CodeAccessorMethod::AccessorType type );

       /**
         * create a new CodeOperation object belonging to this CodeDocument.
         * @return      CodeOperation
         */
        virtual CodeOperation * newCodeOperation( UMLOperation * op );

	/**
         * Save the XMI representation of this object
         * @return      bool    status of save
         */
        virtual bool saveToXMI ( QDomDocument & doc, QDomElement & root );

        /**
         * load params from the appropriate XMI element node.
         */
        virtual void loadFromXMI ( QDomElement & root );

protected:

       /** set attributes of the node that represents this class
         * in the XMI document.
         */
        virtual void setAttributesOnNode ( QDomDocument & doc, QDomElement & blockElement);

        /** set the class attributes of this object from
         * the passed element node.
         */
        virtual void setAttributesFromNode ( QDomElement & element);

	void addOrUpdateCodeClassFieldMethodsInCodeBlock(QPtrList<CodeClassField> &list, CPPClassDeclarationBlock * codeBlock); 

	// add the declaration text blocks for various classfields
	void declareClassFields (QPtrList<CodeClassField> & list , HierarchicalCodeBlock * hCodeBlock ); 

	// CPPClassDeclarationBlock * getClassDecl ( );
	bool forceDoc ();

	void updateContent();

private:

	HierarchicalCodeBlock * constructorBlock;
	HierarchicalCodeBlock * operationsBlock;

	ClassifierInfo * info;
	QString fileName; // Just for our convience in creating code
	QString endLine; // characters for ending line. Just for our convience in creating code
	QString CPPClassName;

	void init ( );


};

#endif // CPPCLASSIFIERCODEDOCUMENT_H
