

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

/*  This code generated by:
 *      Author : thomas
 *      Date   : Mon Sep 1 2003
 */

#ifndef CPPHEADERCLASSDECLARATIONBLOCK_H
#define CPPHEADERCLASSDECLARATIONBLOCK_H

#include <qstring.h>

#include "cppheadercodedocument.h"
#include "../ownedhierarchicalcodeblock.h"

class CPPHeaderClassDeclarationBlock : public OwnedHierarchicalCodeBlock
{
	Q_OBJECT
public:

	// Constructors/Destructors
	//  

	/**
	 * Empty Constructor
	 */
	CPPHeaderClassDeclarationBlock ( CPPHeaderCodeDocument * parentDoc, QString start = "", QString endText = "}", QString comment = "");

	/**
	 * Empty Destructor
	 */
	virtual ~CPPHeaderClassDeclarationBlock ( );

       /**
         * Save the XMI representation of this object
         * @return      bool    status of save
         */
        virtual bool saveToXMI ( QDomDocument & doc, QDomElement & root );

	virtual void loadFromXMI ( QDomElement & root ); 

protected:

        /** set the class attributes from a passed object
         */
        virtual void setAttributesFromObject (TextBlock * obj);

	/**
	 * Update the start/end text of this codeblock.
	 */
	void updateContent ( );

private:

	void init (CPPHeaderCodeDocument * parent, QString comment);

};

#endif // CPPHEADERCLASSDECLARATIONBLOCK_H
