

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

/*  This code generated by:
 *      Author : thomas
 *      Date   : Mon Sep 1 2003
 */

#ifndef CPPSOURCECLASSDECLARATIONBLOCK_H
#define CPPSOURCECLASSDECLARATIONBLOCK_H

#include <qstring.h>

#include "cppsourcecodedocument.h"
#include "../ownedhierarchicalcodeblock.h"

class CPPSourceClassDeclarationBlock : public OwnedHierarchicalCodeBlock
{
	Q_OBJECT
public:

	// Constructors/Destructors
	//  

	/**
	 * Empty Constructor
	 */
	CPPSourceClassDeclarationBlock ( CPPSourceCodeDocument * parentDoc, QString start = "", QString endText = "}", QString comment = "");

	/**
	 * Empty Destructor
	 */
	virtual ~CPPSourceClassDeclarationBlock ( );

protected:

	/**
	 * Update the start/end text of this codeblock.
	 */
	void updateContent ( );

private:

	void init (CPPSourceCodeDocument * parent, QString comment);

};

#endif // CPPSOURCECLASSDECLARATIONBLOCK_H
