
/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

/*  This code generated by:
 *      Author : thomas
 *      Date   : Fri Jun 20 2003
 */

#ifndef CPPSOURCECODEACCESSORMETHOD_H
#define CPPSOURCECODEACCESSORMETHOD_H

#include <qstring.h>

#include "../codeaccessormethod.h"

class CodeClassField;

class CPPSourceCodeAccessorMethod : public CodeAccessorMethod
{
    Q_OBJECT
public:

    // Constructors/Destructors
    //

    /**
     * Empty Constructor
     */
    CPPSourceCodeAccessorMethod ( CodeClassField * field, CodeAccessorMethod::AccessorType type);

    /**
     * Empty Destructor
     */
    virtual ~CPPSourceCodeAccessorMethod ( );

    /**
     * Must be called before this object is usable
     */
    void update();

protected:

    virtual void updateMethodDeclaration();
    virtual void updateContent();

private:

};

#endif // CPPSOURCECODEACCESSORMETHOD_H
