[Desktop Entry]
Encoding=UTF-8
Type=Service
Exec=blubb
Comment=PHP Language Support
Comment[ca]=Implementació del llenguatge PHP
Comment[ca@valencia]=Implementació del llenguatge PHP
Comment[cs]=Podpora jazyka PHP
Comment[es]=Implementación del lenguaje PHP
Comment[fr]=Prise en charge du langage PHP
Comment[it]=Supporto al linguaggio PHP
Comment[nl]=Ondersteuning van de PHP-taal
Comment[pt]=Suporte à Linguagem PHP
Comment[sk]=Jazyková podpora PHP
Comment[sv]=Stöd för språket PHP
Comment[uk]=Підтримка мови PHP
Comment[x-test]=xxPHP Language Supportxx
Name=PHP Language Support
Name[ca]=Implementació del llenguatge PHP
Name[ca@valencia]=Implementació del llenguatge PHP
Name[cs]=Podpora jazyka PHP
Name[es]=Implementación del lenguaje PHP
Name[fr]=Prise en charge du langage PHP
Name[it]=Supporto al linguaggio PHP
Name[nl]=Ondersteuning van de PHP-taal
Name[pt]=Suporte à Linguagem PHP
Name[sk]=Jazyková podpora PHP
Name[sv]=Stöd för språket PHP
Name[uk]=Підтримка мови PHP
Name[x-test]=xxPHP Language Supportxx
ServiceTypes=KDevelop/Plugin
Icon=application-x-php
X-KDE-Library=kdevphplanguagesupport
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Language=Php
X-KDevelop-Args=PHP
X-KDevelop-Interfaces=ILanguageSupport
X-KDevelop-SupportedMimeTypes=application/x-php
X-KDE-PluginInfo-Name=KDevPhpSupport
X-KDE-PluginInfo-Category=Language Support
X-KDevelop-Mode=NoGUI
X-KDevelop-LoadMode=AlwaysOn
