[Desktop Entry]
Encoding=UTF-8
Type=Service
Exec=blubb
Comment=PHP Language Support
Comment[ca]=Implementació del llenguatge PHP
Comment[ca@valencia]=Implementació del llenguatge PHP
Comment[cs]=Podpora jazyka PHP
Comment[da]=Understøttelse af PHP-sproget
Comment[de]=Sprachunterstützung für PHP
Comment[el]=Υποστήριξη γλώσσας PHP
Comment[en_GB]=PHP Language Support
Comment[es]=Implementación del lenguaje PHP
Comment[et]=PHP keele toetus
Comment[eu]=PHP lengoaiaren euskarria
Comment[fi]=PHP-kielen tuki
Comment[fr]=Prise en charge du langage PHP
Comment[gl]=Compatibilidade coa linguaxe PHP
Comment[hu]=PHP nyelvi támogatás
Comment[it]=Supporto al linguaggio PHP
Comment[ka]=PHP ენის მხარდაჭერა
Comment[ko]=PHP 언어 지원
Comment[nb]=PHP språkstøtte
Comment[nl]=Ondersteuning van PHP-taal
Comment[nn]=Støtte for PHP
Comment[pl]=Obsługa języka PHP
Comment[pt]=Suporte da Linguagem PHP
Comment[pt_BR]=Suporte à linguagem PHP
Comment[ru]=Поддержка языка программирования PHP
Comment[sk]=Jazyková podpora PHP
Comment[sl]=Podpora jeziku PHP
Comment[sv]=PHP-språkstöd
Comment[tr]=PHP Dili Desteği
Comment[uk]=Підтримка мови PHP
Comment[x-test]=xxPHP Language Supportxx
Comment[zh_CN]=PHP 语言支持
Comment[zh_TW]=PHP 語言支援
Name=PHP Language Support
Name[ca]=Implementació del llenguatge PHP
Name[ca@valencia]=Implementació del llenguatge PHP
Name[cs]=Podpora jazyka PHP
Name[da]=Understøttelse af PHP-sproget
Name[de]=Sprachunterstützung für PHP
Name[el]=Υποστήριξη γλώσσας PHP
Name[en_GB]=PHP Language Support
Name[es]=Implementación del lenguaje PHP
Name[et]=PHP keele toetus
Name[eu]=PHP lengoaiaren euskarria
Name[fi]=PHP-kielen tuki
Name[fr]=Prise en charge du langage PHP
Name[gl]=Compatibilidade coa linguaxe PHP
Name[hu]=PHP nyelvi támogatás
Name[it]=Supporto al linguaggio PHP
Name[ka]=PHP ენის მხარდაჭერა
Name[ko]=PHP 언어 지원
Name[nb]=PHP språkstøtte
Name[nl]=Ondersteuning van PHP-taal
Name[nn]=Støtte for PHP
Name[pl]=Obsługa języka PHP
Name[pt]=Suporte da Linguagem PHP
Name[pt_BR]=Suporte à linguagem PHP
Name[ru]=Поддержка PHP
Name[sk]=Jazyková podpora PHP
Name[sl]=Podpora jeziku PHP
Name[sv]=PHP-språkstöd
Name[tr]=PHP Dili Desteği
Name[uk]=Підтримка мови PHP
Name[x-test]=xxPHP Language Supportxx
Name[zh_CN]=PHP 语言支持
Name[zh_TW]=PHP 語言支援
ServiceTypes=KDevelop/Plugin
Icon=application-x-php
X-KDE-Library=kdevphplanguagesupport
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Language=Php
X-KDevelop-Args=PHP
X-KDevelop-Interfaces=ILanguageSupport
X-KDevelop-SupportedMimeTypes=application/x-php
X-KDE-PluginInfo-Name=KDevPhpSupport
X-KDE-PluginInfo-Category=Language Support
X-KDevelop-Mode=NoGUI
X-KDevelop-LoadMode=AlwaysOn
