/*
    This file is part of the KDE project
    SPDX-FileCopyrightText: 2012 Milian Wolff <mail@milianw.de>

    SPDX-License-Identifier: LGPL-2.0-or-later
*/
#ifndef KDEVPHP_VERSION_H
#define KDEVPHP_VERSION_H

#include <kdeversion.h>

#define KDEVPHP_MAJOR_VERSION @KDEVPHP_VERSION_MAJOR@
#define KDEVPHP_MINOR_VERSION @KDEVPHP_VERSION_MINOR@
#define KDEVPHP_PATCH_VERSION @KDEVPHP_VERSION_PATCH@

#define KDEVPHP_VERSION_STR "@KDEVPHP_VERSION_MAJOR@.@KDEVPHP_VERSION_MINOR@.@KDEVPHP_VERSION_PATCH@"

#define KDEVPHP_VERSION KDE_MAKE_VERSION(@KDEVPHP_VERSION_MAJOR@, @KDEVPHP_VERSION_MINOR@, @KDEVPHP_VERSION_PATCH@)

#endif
